### ISSUE TITLE
Pickle File Generation

### ISSUE THREAD

**Issue by YikunHan42** [emmaking-smith/Modular_Latent_Space#1]
Hi,

Great work and thanks for your open-source code! I had no problems following your user guide and existing example. However, I noticed that you mentioned pickle data is the Pyrfume data, but I couldn't find any existing pickle file in the pyrfume-data repository. Did you generate it yourself? If so, which protocol did you use for pickle data generation?

I generated a pickle file for a custom dataset and modified the arguments for the fragrance part, but I am still encountering errors.

When I set protocol to 5, it returns
```
Traceback (most recent call last):
  File "predict_fragrance.py", line 266, in <module>
    main()
  File "predict_fragrance.py", line 157, in main
    df = pd.read_pickle(path_to_fragrance_data)
  File "D:\Software\Anaconda\envs\transfer_learning\lib\site-packages\pandas\io\pickle.py", line 217, in read_pickle
    return pickle.load(handles.handle)  # type: ignore[arg-type]
ValueError: unsupported pickle protocol: 5
```

When I set protocol to 4, it returns
```
Traceback (most recent call last):
  File "D:\Software\Anaconda\envs\transfer_learning\lib\site-packages\pandas\io\pickle.py", line 217, in read_pickle
    return pickle.load(handles.handle)  # type: ignore[arg-type]
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from 'D:\\Software\\Anaconda\\envs\\transfer_learning\\lib\\site-packages\\pandas\\_libs\\internals.cp37-win_amd64.pyd'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict_fragrance.py", line 266, in <module>
    main()
  File "predict_fragrance.py", line 157, in main
    df = pd.read_pickle(path_to_fragrance_data)
  File "D:\Software\Anaconda\envs\transfer_learning\lib\site-packages\pandas\io\pickle.py", line 222, in read_pickle
    return pc.load(handles.handle, encoding=None)
  File "D:\Software\Anaconda\envs\transfer_learning\lib\site-packages\pandas\compat\pickle_compat.py", line 274, in load
    return up.load()
  File "D:\Software\Anaconda\envs\transfer_learning\lib\pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "D:\Software\Anaconda\envs\transfer_learning\lib\pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "D:\Software\Anaconda\envs\transfer_learning\lib\site-packages\pandas\compat\pickle_compat.py", line 206, in find_class
    return super().find_class(module, name)
  File "D:\Software\Anaconda\envs\transfer_learning\lib\pickle.py", line 1430, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module 'pandas._libs.internals' has no attribute '_unpickle_block'
```

I have set up the environment following the user guide, so the Python version and all package versions should be the same. Do you have any idea what might be causing these errors?

Thanks for your help in advance.

**Comment by emmaking-smith** [comment]
I did some minor reformatting and clean up of Pyrfume's Leffingwell dataset.  Their repo is linked [here](https://github.com/pyrfume/pyrfume-data/tree/main). I believe they use csv files - out of personal preference, I like using pickle files.

I'm not sure why you are having so much trouble loading your custom pickle file.  When I make them, I always use the pandas.to_pickle() function (see [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html) for the documentation).  But worse comes to worst, you can just change the line of code to pd.read_csv() instead.

Out of curiosity, can you load in either of the pickle files in the `fragrance/data/` directory?

**Comment by YikunHan42** [comment]
Thanks, I can load both of the pickle files in the original directory. I think my code for converting csv to pickle may use a different package version and cause the problem. As you said, I just changed it to `pd.read_csv()` and it works well.
